// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainCompManagement.DAL;

#nullable disable

namespace TrainCompManagement.DAL.Migrations
{
    [DbContext(typeof(TrainCompManagementDbContext))]
    [Migration("20230713170302_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainCompManagement.DAL.Entities.TrainInformation", b =>
                {
                    b.Property<long>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrainId"));

                    b.Property<bool>("IsQuantityAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TrainId");

                    b.HasIndex("UniqueNumber")
                        .IsUnique();

                    b.ToTable("TrainInformation");
                });

            modelBuilder.Entity("TrainCompManagement.DAL.Entities.TrainTreePath", b =>
                {
                    b.Property<long>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PathId"));

                    b.Property<long?>("AncestorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DescendantId")
                        .HasColumnType("bigint");

                    b.HasKey("PathId");

                    b.HasIndex("AncestorId");

                    b.HasIndex("DescendantId");

                    b.ToTable("TrainTreePath");
                });

            modelBuilder.Entity("TrainCompManagement.DAL.Entities.TrainTreePath", b =>
                {
                    b.HasOne("TrainCompManagement.DAL.Entities.TrainInformation", "Ancestor")
                        .WithMany("Parent")
                        .HasForeignKey("AncestorId");

                    b.HasOne("TrainCompManagement.DAL.Entities.TrainInformation", "Descendant")
                        .WithMany("Children")
                        .HasForeignKey("DescendantId");

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("TrainCompManagement.DAL.Entities.TrainInformation", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
